export const CITY_OPTIONS = [
  { code: 'AMS', name: 'Amsterdam' },
  { code: 'ANF', name: 'Antofagasta' },
  { code: 'AJU', name: 'Aracaju' },
  { code: 'ARI', name: 'Arica' },
  { code: 'AUA', name: 'Aruba' },
  { code: 'ASU', name: 'Assunção' },
  { code: 'ATH', name: 'Atenas' },
  { code: 'ATL', name: 'Atlanta' },
  { code: 'BKK', name: 'Bangkok' },
  { code: 'BCN', name: 'Barcelona' },
  { code: 'BRC', name: 'Bariloche' },
  { code: 'CNF', name: 'Belo Horizonte' },
  { code: 'PLU', name: 'Belo Horizonte' },
  { code: 'BEL', name: 'Belém' },
  { code: 'BVB', name: 'Boa Vista' },
  { code: 'BOG', name: 'Bogotá' },
  { code: 'BYO', name: 'Bonito' },
  { code: 'BOS', name: 'Boston' },
  { code: 'BSB', name: 'Brasília' },
  { code: 'BRU', name: 'Bruxelas' },
  { code: 'AEP', name: 'Buenos Aires' },
  { code: 'EZE', name: 'Buenos Aires' },
  { code: 'CFB', name: 'Cabo Frio' },
  { code: 'CJC', name: 'Calama' },
  { code: 'CLV', name: 'Caldas Novas' },
  { code: 'CPV', name: 'Campina Grande' },
  { code: 'VCP', name: 'Campinas' },
  { code: 'CGR', name: 'Campo Grande' },
  { code: 'CUN', name: 'Cancún' },
  { code: 'CKS', name: 'Carajás' },
  { code: 'CTG', name: 'Cartagena' },
  { code: 'CAU', name: 'Caruaru' },
  { code: 'CAC', name: 'Cascavel' },
  { code: 'CXJ', name: 'Caxias do Sul' },
  { code: 'XAP', name: 'Chapecó' },
  { code: 'ORD', name: 'Chicago' },
  { code: 'MEX', name: 'Cidade do México' },
  { code: 'CPH', name: 'Copenhage' },
  { code: 'CPO', name: 'Copiapó' },
  { code: 'CGB', name: 'Cuiabá' },
  { code: 'CUR', name: 'Curaçao' },
  { code: 'CWB', name: 'Curitiba' },
  { code: 'CUZ', name: 'Cusco' },
  { code: 'DFW', name: 'Dallas' },
  { code: 'DXB', name: 'Dubai' },
  { code: 'DUB', name: 'Dublin' },
  { code: 'DBV', name: 'Dubrovnik' },
  { code: 'FEN', name: 'Fernando de Noronha' },
  { code: 'FLN', name: 'Florianópolis' },
  { code: 'FLL', name: 'Fort Lauderdale' },
  { code: 'FOR', name: 'Fortaleza' },
  { code: 'IGU', name: 'Foz do Iguaçu' },
  { code: 'FRA', name: 'Frankfurt' },
  { code: 'GYN', name: 'Goiânia' },
  { code: 'HAV', name: 'Havana' },
  { code: 'HKG', name: 'Hong Kong' },
  { code: 'HOU', name: 'Houston' },
  { code: 'IAH', name: 'Houston' },
  { code: 'IBZ', name: 'Ibiza' },
  { code: 'IOS', name: 'Ilhéus' },
  { code: 'IPN', name: 'Ipatinga' },
  { code: 'JJG', name: 'Jaguaruna' },
  { code: 'JJD', name: 'Jericoacoara' },
  { code: 'JNB', name: 'Johanesburgo' },
  { code: 'JOI', name: 'Joinville' },
  { code: 'JPA', name: 'João Pessoa' },
  { code: 'IZA', name: 'Juiz de Fora' },
  { code: 'JDF', name: 'Juiz de Fora' },
  { code: 'KEF', name: 'Keflavik' },
  { code: 'LEC', name: 'Lençóis' },
  { code: 'LIM', name: 'Lima' },
  { code: 'LIS', name: 'Lisboa' },
  { code: 'LGW', name: 'Londres' },
  { code: 'LHR', name: 'Londres' },
  { code: 'LDB', name: 'Londrina' },
  { code: 'LAX', name: 'Los Angeles' },
  { code: 'MCP', name: 'Macapá' },
  { code: 'MCZ', name: 'Maceió' },
  { code: 'MAD', name: 'Madri' },
  { code: 'MAO', name: 'Manaus' },
  { code: 'MGF', name: 'Maringá' },
  { code: 'MDZ', name: 'Mendoza' },
  { code: 'MIA', name: 'Miami' },
  { code: 'LIN', name: 'Milão' },
  { code: 'MXP', name: 'Milão' },
  { code: 'MOC', name: 'Montes Claros' },
  { code: 'MVD', name: 'Montevidéu' },
  { code: 'YUL', name: 'Montreal' },
  { code: 'MUC', name: 'Munique' },
  { code: 'NAT', name: 'Natal' },
  { code: 'NVT', name: 'Navegantes' },
  { code: 'EWR', name: 'Nova York' },
  { code: 'JFK', name: 'Nova York' },
  { code: 'LGA', name: 'Nova York' },
  { code: 'MCO', name: 'Orlando' },
  { code: 'OSL', name: 'Oslo' },
  { code: 'PMW', name: 'Palmas' },
  { code: 'PTY', name: 'Panamá' },
  { code: 'CDG', name: 'Paris' },
  { code: 'ORY', name: 'Paris' },
  { code: 'PNZ', name: 'Petrolina' },
  { code: 'OPO', name: 'Porto' },
  { code: 'POA', name: 'Porto Alegre' },
  { code: 'BPS', name: 'Porto Seguro' },
  { code: 'PVH', name: 'Porto Velho' },
  { code: 'PPB', name: 'Presidente Prudente' },
  { code: 'PMC', name: 'Puerto Montt' },
  { code: 'PUQ', name: 'Punta Arenas' },
  { code: 'PUJ', name: 'Punta Cana' },
  { code: 'PDP', name: 'Punta del Este' },
  { code: 'UIO', name: 'Quito' },
  { code: 'REC', name: 'Recife' },
  { code: 'RKV', name: 'Reykjavik' },
  { code: 'RAO', name: 'Ribeirão Preto' },
  { code: 'RBR', name: 'Rio Branco' },
  { code: 'GIG', name: 'Rio de Janeiro' },
  { code: 'SDU', name: 'Rio de Janeiro' },
  { code: 'CIA', name: 'Roma' },
  { code: 'FCO', name: 'Roma' },
  { code: 'SSA', name: 'Salvador' },
  { code: 'ADZ', name: 'San Andres' },
  { code: 'SJO', name: 'San José' },
  { code: 'VVI', name: 'Santa C La Sierra' },
  { code: 'STM', name: 'Santarém' },
  { code: 'SCL', name: 'Santiago' },
  { code: 'GEL', name: 'Santo Ângelo' },
  { code: 'GMP', name: 'Seul' },
  { code: 'ICN', name: 'Seul' },
  { code: 'SJP', name: 'São José do Rio Preto' },
  { code: 'SJK', name: 'São José dos Campos' },
  { code: 'SLZ', name: 'São Luís' },
  { code: 'CGH', name: 'São Paulo' },
  { code: 'GRU', name: 'São Paulo' },
  { code: 'TPE', name: 'Taipé' },
  { code: 'TSA', name: 'Taipé' },
  { code: 'TPA', name: 'Tampa' },
  { code: 'ZCO', name: 'Temuco' },
  { code: 'THE', name: 'Teresina' },
  { code: 'YYZ', name: 'Toronto' },
  { code: 'TQO', name: 'Tulum' },
  { code: 'HND', name: 'Tóquio' },
  { code: 'NRT', name: 'Tóquio' },
  { code: 'UDI', name: 'Uberlândia' },
  { code: 'YVR', name: 'Vancouver' },
  { code: 'WAW', name: 'Varsóvia' },
  { code: 'VCE', name: 'Veneza' },
  { code: 'VIX', name: 'Vitória' },
  { code: 'VDC', name: 'Vitória da Conquista' },
  { code: 'DCA', name: 'Washington' },
  { code: 'IAD', name: 'Washington' },
  { code: 'ZAG', name: 'Zagreb' },
  { code: 'ZRH', name: 'Zurique' },
]
