CIDADES = {
    "ADZ": "San Andres",
    "AEP": "Buenos Aires",
    "AJU": "Aracaju",
    "AMS": "Amsterdam",
    "ANF": "Antofagasta",
    "ARI": "Arica",
    "ASU": "Assunção",
    "ATH": "Atenas",
    "ATL": "Atlanta",
    "AUA": "Aruba",
    "BCN": "Barcelona",
    "BEL": "Belém",
    "BKK": "Bangkok",
    "BOG": "Bogotá",
    "BOS": "Boston",
    "BPS": "Porto Seguro",
    "BRC": "Bariloche",
    "BRU": "Bruxelas",
    "BSB": "Brasília",
    "BVB": "Boa Vista",
    "BYO": "Bonito",
    "CAC": "Cascavel",
    "CAU": "Caruaru",
    "CDG": "Paris",
    "CFB": "Cabo Frio",
    "CGB": "Cuiabá",
    "CGH": "São Paulo",
    "CGR": "Campo Grande",
    "CIA": "Roma",
    "CJC": "Calama",
    "CKS": "Carajás",
    "CLV": "Caldas Novas",
    "CNF": "Belo Horizonte",
    "CPH": "Copenhage",
    "CPO": "Copiapó",
    "CPV": "Campina Grande",
    "CTG": "Cartagena",
    "CUN": "Cancún",
    "CUR": "Curaçao",
    "CUZ": "Cusco",
    "CWB": "Curitiba",
    "CXJ": "Caxias do Sul",
    "DBV": "Dubrovnik",
    "DCA": "Washington",
    "DFW": "Dallas",
    "DUB": "Dublin",
    "DXB": "Dubai",
    "EWR": "Nova York",
    "EZE": "Buenos Aires",
    "FCO": "Roma",
    "FEN": "Fernando de Noronha",
    "FLL": "Fort Lauderdale",
    "FLN": "Florianópolis",
    "FOR": "Fortaleza",
    "FRA": "Frankfurt",
    "GEL": "Santo Ângelo",
    "GIG": "Rio de Janeiro",
    "GMP": "Seul",
    "GRU": "São Paulo",
    "GYN": "Goiânia",
    "HAV": "Havana",
    "HKG": "Hong Kong",
    "HND": "Tóquio",
    "HOU": "Houston",
    "IAD": "Washington",
    "IAH": "Houston",
    "IBZ": "Ibiza",
    "ICN": "Seul",
    "IGU": "Foz do Iguaçu",
    "IOS": "Ilhéus",
    "IPN": "Ipatinga",
    "IZA": "Juiz de Fora",
    "JDF": "Juiz de Fora",
    "JFK": "Nova York",
    "JJD": "Jericoacoara",
    "JJG": "Jaguaruna",
    "JNB": "Johanesburgo",
    "JOI": "Joinville",
    "JPA": "João Pessoa",
    "KEF": "Keflavik",
    "LAX": "Los Angeles",
    "LDB": "Londrina",
    "LEC": "Lençóis",
    "LGA": "Nova York",
    "LGW": "Londres",
    "LHR": "Londres",
    "LIM": "Lima",
    "LIN": "Milão",
    "LIS": "Lisboa",
    "MAD": "Madri",
    "MAO": "Manaus",
    "MCO": "Orlando",
    "MCP": "Macapá",
    "MCZ": "Maceió",
    "MDZ": "Mendoza",
    "MEX": "Cidade do México",
    "MGF": "Maringá",
    "MIA": "Miami",
    "MOC": "Montes Claros",
    "MUC": "Munique",
    "MVD": "Montevidéu",
    "MXP": "Milão",
    "NAT": "Natal",
    "NRT": "Tóquio",
    "NVT": "Navegantes",
    "OPO": "Porto",
    "ORD": "Chicago",
    "ORY": "Paris",
    "OSL": "Oslo",
    "PDP": "Punta del Este",
    "PLU": "Belo Horizonte",
    "PMC": "Puerto Montt",
    "PMW": "Palmas",
    "PNZ": "Petrolina",
    "POA": "Porto Alegre",
    "PPB": "Presidente Prudente",
    "PTY": "Panamá",
    "PUJ": "Punta Cana",
    "PUQ": "Punta Arenas",
    "PVH": "Porto Velho",
    "RAO": "Ribeirão Preto",
    "RBR": "Rio Branco",
    "REC": "Recife",
    "RKV": "Reykjavik",
    "SCL": "Santiago",
    "SDU": "Rio de Janeiro",
    "SJK": "São José dos Campos",
    "SJO": "San José",
    "SJP": "São José do Rio Preto",
    "SLZ": "São Luís",
    "SSA": "Salvador",
    "STM": "Santarém",
    "THE": "Teresina",
    "TPA": "Tampa",
    "TPE": "Taipé",
    "TQO": "Tulum",
    "TSA": "Taipé",
    "UDI": "Uberlândia",
    "UIO": "Quito",
    "VCE": "Veneza",
    "VCP": "Campinas",
    "VDC": "Vitória da Conquista",
    "VIX": "Vitória",
    "VVI": "Santa C La Sierra",
    "WAW": "Varsóvia",
    "XAP": "Chapecó",
    "YUL": "Montreal",
    "YVR": "Vancouver",
    "YYZ": "Toronto",
    "ZAG": "Zagreb",
    "ZCO": "Temuco",
    "ZRH": "Zurique",
}

CITY_ALIASES = {
    "Caixas do Sul": "Caxias do Sul",
    "Taipei": "Taipé",
    "Taiwan": "Taipé",
}
